// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {account} from '../models';
import {app} from '../models';
import {smtp} from '../models';
import {message} from '../models';
import {pgp} from '../models';
import {smime} from '../models';
import {platform} from '../models';
import {draft} from '../models';
import {contact} from '../models';
import {context} from '../models';

export function CheckRecipientCerts(arg1:Array<string>):Promise<Record<string, boolean>>;

export function CheckRecipientPGPKeys(arg1:Array<string>):Promise<Record<string, boolean>>;

export function CloseWindow():Promise<void>;

export function DeleteDraft(arg1:string):Promise<void>;

export function GetAccount(arg1:string):Promise<account.Account>;

export function GetAllAccountIdentities():Promise<Array<app.AccountIdentityGroup>>;

export function GetComposeMode():Promise<app.ComposeMode>;

export function GetDarkComposerBody():Promise<boolean>;

export function GetDraft():Promise<smtp.ComposeMessage>;

export function GetIdentities(arg1:string):Promise<Array<account.Identity>>;

export function GetNativeTitleBar():Promise<boolean>;

export function GetOriginalMessage():Promise<message.Message>;

export function GetPGPEncryptPolicy(arg1:string):Promise<string>;

export function GetPGPKeyForEmail(arg1:string,arg2:string):Promise<pgp.Key>;

export function GetPGPSignPolicy(arg1:string):Promise<string>;

export function GetSMIMECertificateForEmail(arg1:string,arg2:string):Promise<smime.Certificate>;

export function GetSMIMEEncryptPolicy(arg1:string):Promise<string>;

export function GetSMIMESignPolicy(arg1:string):Promise<string>;

export function GetShowTitleBar():Promise<boolean>;

export function GetSystemTheme():Promise<string>;

export function GetThemeMode():Promise<string>;

export function GetWindowDecorationStatus():Promise<platform.WindowDecorationStatus>;

export function HasPGPKey(arg1:string):Promise<boolean>;

export function HasSMIMECertificate(arg1:string):Promise<boolean>;

export function ImportRecipientCert(arg1:string,arg2:string):Promise<void>;

export function ImportRecipientPGPKey(arg1:string,arg2:string):Promise<void>;

export function IsFlatpak():Promise<boolean>;

export function LogFrontend(arg1:string,arg2:string):Promise<void>;

export function LookupHKP(arg1:string):Promise<string>;

export function LookupPGPKey(arg1:string):Promise<string>;

export function LookupWKD(arg1:string):Promise<string>;

export function NotifyStartupComplete():Promise<void>;

export function PickAttachmentFiles():Promise<Array<app.ComposerAttachment>>;

export function PickRecipientCertFile():Promise<string>;

export function PickRecipientPGPKeyFile():Promise<string>;

export function PrepareReply():Promise<smtp.ComposeMessage>;

export function ReadFileAsAttachment(arg1:string):Promise<app.ComposerAttachment>;

export function RefreshWindowConstraints():Promise<void>;

export function SaveDraft(arg1:string,arg2:smtp.ComposeMessage,arg3:string):Promise<draft.Draft>;

export function SearchContacts(arg1:string,arg2:number):Promise<Array<contact.Contact>>;

export function SendMessage(arg1:string,arg2:smtp.ComposeMessage):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
