// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRecipientCerts(arg1) {
  return window['go']['app']['ComposerApp']['CheckRecipientCerts'](arg1);
}

export function CheckRecipientPGPKeys(arg1) {
  return window['go']['app']['ComposerApp']['CheckRecipientPGPKeys'](arg1);
}

export function CloseWindow() {
  return window['go']['app']['ComposerApp']['CloseWindow']();
}

export function DeleteDraft(arg1) {
  return window['go']['app']['ComposerApp']['DeleteDraft'](arg1);
}

export function GetAccount(arg1) {
  return window['go']['app']['ComposerApp']['GetAccount'](arg1);
}

export function GetAllAccountIdentities() {
  return window['go']['app']['ComposerApp']['GetAllAccountIdentities']();
}

export function GetComposeMode() {
  return window['go']['app']['ComposerApp']['GetComposeMode']();
}

export function GetDarkComposerBody() {
  return window['go']['app']['ComposerApp']['GetDarkComposerBody']();
}

export function GetDraft() {
  return window['go']['app']['ComposerApp']['GetDraft']();
}

export function GetIdentities(arg1) {
  return window['go']['app']['ComposerApp']['GetIdentities'](arg1);
}

export function GetNativeTitleBar() {
  return window['go']['app']['ComposerApp']['GetNativeTitleBar']();
}

export function GetOriginalMessage() {
  return window['go']['app']['ComposerApp']['GetOriginalMessage']();
}

export function GetPGPEncryptPolicy(arg1) {
  return window['go']['app']['ComposerApp']['GetPGPEncryptPolicy'](arg1);
}

export function GetPGPKeyForEmail(arg1, arg2) {
  return window['go']['app']['ComposerApp']['GetPGPKeyForEmail'](arg1, arg2);
}

export function GetPGPSignPolicy(arg1) {
  return window['go']['app']['ComposerApp']['GetPGPSignPolicy'](arg1);
}

export function GetSMIMECertificateForEmail(arg1, arg2) {
  return window['go']['app']['ComposerApp']['GetSMIMECertificateForEmail'](arg1, arg2);
}

export function GetSMIMEEncryptPolicy(arg1) {
  return window['go']['app']['ComposerApp']['GetSMIMEEncryptPolicy'](arg1);
}

export function GetSMIMESignPolicy(arg1) {
  return window['go']['app']['ComposerApp']['GetSMIMESignPolicy'](arg1);
}

export function GetShowTitleBar() {
  return window['go']['app']['ComposerApp']['GetShowTitleBar']();
}

export function GetSystemTheme() {
  return window['go']['app']['ComposerApp']['GetSystemTheme']();
}

export function GetThemeMode() {
  return window['go']['app']['ComposerApp']['GetThemeMode']();
}

export function GetWindowDecorationStatus() {
  return window['go']['app']['ComposerApp']['GetWindowDecorationStatus']();
}

export function HasPGPKey(arg1) {
  return window['go']['app']['ComposerApp']['HasPGPKey'](arg1);
}

export function HasSMIMECertificate(arg1) {
  return window['go']['app']['ComposerApp']['HasSMIMECertificate'](arg1);
}

export function ImportRecipientCert(arg1, arg2) {
  return window['go']['app']['ComposerApp']['ImportRecipientCert'](arg1, arg2);
}

export function ImportRecipientPGPKey(arg1, arg2) {
  return window['go']['app']['ComposerApp']['ImportRecipientPGPKey'](arg1, arg2);
}

export function IsFlatpak() {
  return window['go']['app']['ComposerApp']['IsFlatpak']();
}

export function LogFrontend(arg1, arg2) {
  return window['go']['app']['ComposerApp']['LogFrontend'](arg1, arg2);
}

export function LookupHKP(arg1) {
  return window['go']['app']['ComposerApp']['LookupHKP'](arg1);
}

export function LookupPGPKey(arg1) {
  return window['go']['app']['ComposerApp']['LookupPGPKey'](arg1);
}

export function LookupWKD(arg1) {
  return window['go']['app']['ComposerApp']['LookupWKD'](arg1);
}

export function NotifyStartupComplete() {
  return window['go']['app']['ComposerApp']['NotifyStartupComplete']();
}

export function PickAttachmentFiles() {
  return window['go']['app']['ComposerApp']['PickAttachmentFiles']();
}

export function PickRecipientCertFile() {
  return window['go']['app']['ComposerApp']['PickRecipientCertFile']();
}

export function PickRecipientPGPKeyFile() {
  return window['go']['app']['ComposerApp']['PickRecipientPGPKeyFile']();
}

export function PrepareReply() {
  return window['go']['app']['ComposerApp']['PrepareReply']();
}

export function ReadFileAsAttachment(arg1) {
  return window['go']['app']['ComposerApp']['ReadFileAsAttachment'](arg1);
}

export function RefreshWindowConstraints() {
  return window['go']['app']['ComposerApp']['RefreshWindowConstraints']();
}

export function SaveDraft(arg1, arg2, arg3) {
  return window['go']['app']['ComposerApp']['SaveDraft'](arg1, arg2, arg3);
}

export function SearchContacts(arg1, arg2) {
  return window['go']['app']['ComposerApp']['SearchContacts'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['app']['ComposerApp']['SendMessage'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['app']['ComposerApp']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['ComposerApp']['Startup'](arg1);
}
